Feature 167 metaform versioning
Metatavu/metaform-api pull request #168
Opened 2022-06-16 11:09 UTC by Chi-Chu319

resolves #167

2022-06-16 11:10 UTC, Chi-Chu319 commented on src/main/java/fi/metatavu/metaform/server/metaforms/MetaformVersionController.java
> + * Metaform controller
```suggestion
 * Metaform version controller
```

2022-06-16 11:11 UTC, Chi-Chu319 commented on src/main/java/fi/metatavu/metaform/server/persistence/dao/MetaformVersionDAO.java
> +   * @return created Metaform
```suggestion
   * @return created Metaform version
```

2022-06-16 11:12 UTC, Chi-Chu319 commented on src/test/java/fi/metatavu/metaform/test/functional/builder/impl/MetaformVersionTestBuilderResource.java
> +     * @param metaformId metaform id
```suggestion
    /**
     * Finds a metaform version
     *
     * @param metaformId metaform id
```

2022-06-16 13:41 UTC, Chi-Chu319 commented on src/main/java/fi/metatavu/metaform/server/rest/translate/MetaformVersionTranslator.java
> +//     TODO check data translation
```suggestion
```

2022-06-17 05:05 UTC, anttileppa requested changes

2022-06-17 05:05 UTC, anttileppa commented on src/main/java/fi/metatavu/metaform/server/metaforms/MetaformVersionController.java
> +package fi.metatavu.metaform.server.metaforms;
All new code should be Kotlin

2022-06-17 07:19 UTC, anttileppa requested changes

2022-06-17 07:19 UTC, anttileppa commented on src/main/java/fi/metatavu/metaform/server/metaforms/MetaformVersionController.java
> +  public MetaformVersion find(UUID metaformVersionId) {
```suggestion
  public MetaformVersion findMetaformVersionById(UUID metaformVersionId) {
```

2022-06-17 07:19 UTC, anttileppa commented on src/main/java/fi/metatavu/metaform/server/metaforms/MetaformVersionController.java
> +  public List<MetaformVersion> listByMetaform(Metaform metaform) {
```suggestion
  public List<MetaformVersion> listMetaformVersionsByMetaform(Metaform metaform) {
```

2022-06-17 07:19 UTC, anttileppa commented on src/main/java/fi/metatavu/metaform/server/metaforms/MetaformVersionController.java
> +  public List<MetaformVersion> list() {
This sounds like dangerous method because it returns all versions from ALL forms

2022-06-17 07:19 UTC, anttileppa commented on src/main/java/fi/metatavu/metaform/server/metaforms/MetaformVersionController.java
> +  public void delete(MetaformVersion metaformVersion) {
```suggestion
  public void deleteMetaformVersion(MetaformVersion metaformVersion) {
```

2022-06-17 07:19 UTC, anttileppa commented on src/test/java/fi/metatavu/metaform/test/functional/tests/VersionTestsIT.kt
> +package fi.metatavu.metaform.test.functional.tests
There should be permission tests, that assert that only users with proper permissions may access these endpoints

2022-06-17 07:19 UTC, anttileppa commented on src/test/java/fi/metatavu/metaform/test/functional/tests/VersionTestsIT.kt
> +package fi.metatavu.metaform.test.functional.tests
Add also tests for invalid inputs

2022-06-17 07:19 UTC, anttileppa commented on src/main/java/fi/metatavu/metaform/server/rest/V1ApiImpl.java
> +      return createForbidden(YOU_ARE_NOT_ALLOWED_TO_UPDATE_METAFORMS);
YOU_ARE_NOT_ALLOWED_TO_UPDATE_METAFORMS?

2022-06-17 07:19 UTC, anttileppa commented on src/main/java/fi/metatavu/metaform/server/rest/V1ApiImpl.java
> +      return createForbidden("You are not allowed to delete Metaforms");
Fix the error message

2022-06-17 07:19 UTC, anttileppa commented on src/main/java/fi/metatavu/metaform/server/rest/V1ApiImpl.java
> +      return createForbidden("You are not allowed to delete Metaforms");
Fix the error message

2022-06-17 07:19 UTC, anttileppa commented on src/main/java/fi/metatavu/metaform/server/rest/V1ApiImpl.java
> +    ObjectMapper objectMapper = new ObjectMapper();
Serialization should be done in the controller, not in REST API

2022-06-17 07:19 UTC, anttileppa commented on src/main/java/fi/metatavu/metaform/server/persistence/model/Metadata.kt
> +abstract class Metadata {
Add docs

2022-06-17 07:19 UTC, anttileppa commented on src/main/java/fi/metatavu/metaform/server/metaforms/MetaformVersionController.java
> +          String data,
Serialize data in controller

2022-06-17 10:24 UTC, anttileppa requested changes

2022-06-17 10:24 UTC, anttileppa commented on src/main/java/fi/metatavu/metaform/server/rest/V1ApiImpl.java
> +      return createForbidden(YOU_ARE_NOT_ALLOWED_TO_LIST_METAFORM_VERSIONS);
We are not actually listing anything here, so maybe find?

2022-06-17 10:24 UTC, anttileppa commented on src/main/java/fi/metatavu/metaform/server/rest/V1ApiImpl.java
> +    return createOk(metaformVersionTranslator.translateMetaformVersion(metaformVersion));
It would be better to use custom error and capture it here? (eg. MalformedVersionJsonException)

2022-06-17 10:24 UTC, anttileppa commented on src/main/java/fi/metatavu/metaform/server/metaforms/MetaformVersionController.java
> +      return null;
This is a bit bad practise, use custom exception

2022-06-20 09:27 UTC, merged